# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='Dept',
        ),
        migrations.AddField(
            model_name='employee',
            name='Emp_pic',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
